import {
    populateDefaultValues
} from '../../component_maker_helpers/prop_value_from_string.js'
import faker from '../../faker.js'

// get's fake props for a component using it's react-docgen generated meta data
// if the fakeProps property is already there, just returns that
// else returns fake props generated by faker merged with default props, if any
function getFakeProps(component) {
    let fakeProps

    if (component.fakeProps) {
        return component.fakePropss
    } else {
        return populateDefaultValues(
            component.props,
            faker(component.props, { optional: false })
        )
    }
}

// just takes a components react-docgen generated object
// get's the path from there
// loads the components
// gets the components fake props
// and sends it across
// TODO - should also send across the css associated with the component
export default function loadComponentFromPath(item) {
    return SystemJS.import(item.path)
        .then(com => {
            const fakeProps = getFakeProps(item)

            return {
                component: com,
                fakeProps
            }
        })
}
